GET http://localhost:5150/games

###
// the purpose of '###' is to separate the request 
GET http://localhost:5150/games/1


###
POST http://localhost:5150/games
//defining content type  so that we can tell our API what kind of content we are seding overthere 
Content-Type: application/json

{
    "name":"Street Chser 3",
    "genreId":3,
    "price":32.99,
    "releaseDate":"2014-12-18"
}
//define our payload of our game we are going to create it as per CreateGameDto

###
//for put endpoint
PUT http://localhost:5150/games/1
Content-Type: application/json

{
    "name":"Total SIMON RACE Turboo",
    "genreId":1,
    "price":18.9779,
    "releaseDate":"2033-02-18"
}

###

DELETE http://localhost:5150/games/2